fix: enhance bootstrap script logging and error handling in workflows

diff --git a/.github/workflows/selfhosted.yml b/.github/workflows/selfhosted.yml
--- a/.github/workflows/selfhosted.yml
+++ b/.github/workflows/selfhosted.yml
@@ -17,6 +17,7 @@ jobs:
         sudo apt-get update
         sudo apt-get install -y \
           autoconf \
+          autoconf2.69 \
           automake \
           autopoint \
           bison \
@@ -56,7 +57,15 @@ jobs:
       id: bootstrap
       run: |
         set -o pipefail
-        TARGET_ARCH=${{ matrix.TARGET_ARCH }} ./scripts/bootstrap.sh | tee ./scripts/bootstrap.log
+        TARGET_ARCH=${{ matrix.TARGET_ARCH }} ./scripts/bootstrap.sh | tee ./scripts/bootstrap.log | grep "==>"
+
+        # Check if the bootstrap script completed successfully
+        if [ "${PIPESTATUS[0]}" -ne 0 ]; then
+          echo "Bootstrap script failed"
+          # display the last 20 lines of the log for debugging
+          tail -n 20 ./scripts/bootstrap.log
+          exit 1
+        fi
 
     - name: Upload bootstrap rootfs
       uses: actions/upload-artifact@v4
