fix: update bootstrap script logging and error handling

diff --git a/.github/workflows/selfhosted.yml b/.github/workflows/selfhosted.yml
--- a/.github/workflows/selfhosted.yml
+++ b/.github/workflows/selfhosted.yml
@@ -71,29 +71,19 @@ jobs:
         id: bootstrap
         run: |
           set -o pipefail
-          TARGET_ARCH=${{ matrix.TARGET_ARCH }} ${{ github.workspace }}/scripts/bootstrap.sh | tee ${{ github.workspace }}/scripts/bootstrap.log | grep --line-buffered "==>"
+          TARGET_ARCH=${{ matrix.TARGET_ARCH }} ${{ github.workspace }}/scripts/bootstrap.sh > ${{ github.workspace }}/scripts/bootstrap.log 2>&1 &
 
-          # Check if the bootstrap script completed successfully
-          if [ "${PIPESTATUS[0]}" -ne 0 ]; then
-            echo "Bootstrap script failed"
-            # display the last 20 lines of the log for debugging
-            tail -n 20 ./scripts/bootstrap.log
+          tail -F ${{ github.workspace }}/scripts/bootstrap.log | grep --line-buffered -E "^==>" &
+
+          wait $!
+
+          # If it failed, print the last 50 lines of the log for debugging
+          if [ $? -ne 0 ]; then
+            echo "❌ Build failed! Showing last 50 lines:"
+            tail -n 50 ${{ github.workspace }}/scripts/bootstrap.log
             exit 1
           fi
-
-      - name: Upload bootstrap log
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: bootstrap-log
-          path: ${{ github.workspace }}/scripts/bootstrap.log
 
       - name: Remove toolchain in rootfs
         run: |
           rm -rf rootfs/toolchain
-
-      - name: Upload bootstrap rootfs
-        uses: actions/upload-artifact@v4
-        with:
-          name: bootstrap-rootfs
-          path: rootfs/*
